version: "0.1.0"

services:
  web_server:
    image: ehdudtkatka/quant-coin-web:0.1
    container_name: web_server
    restart: always
    ports:
      - "${WEB_PORT}:3000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    env_file: .env.prod
    environment: 
      - REACT_APP_SERVER_PANDAS=${REACT_APP_SERVER_PANDAS}

  pandas_server:
    image: ehdudtkatka/quant-coin-pandas:24f2ce3
    container_name: pandas_server
    restart: always
    ports:
      - "${PANDAS_PORT}:4000"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    env_file: .env.prod
    environment: 
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PORT=4000

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    env_file: .env.prod

# docker-compose --env-file ./.env up -d
  # - env_file path default .env
# docker-compose --env-file ./.env.prod up -d
# docker-compose up -d --build
# docker-compose up -d

# redis-cli -h 127.0.0.1 -p 3001 -a dosimpact