version: "0.1.0"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6000:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    env_file: .env
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - HTTP_USER=admin
      - HTTP_PASSWORD=${HTTP_PASSWORD}
      - REDIS_HOST=
      - REDIS_PORT=6000
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "8081:8081"
# docker-compose --env-file ./.env.dev up -d
# redis-cli -h 127.0.0.1 -p 5001 -a dosimpact
