version: '2'

services:
  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - /Users/dos/DockerVolumns/jenkins_home_v2:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

  postgres:
    image: postgres
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - /Users/dos/DockerVolumns/postgres-data:/var/lib/postgresql/data
  sonarqube:
    image: mwizner/sonarqube:8.9.5-community
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres

networks:
  jenkins: